# Generated by Django 3.1.1 on 2020-09-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_Name', models.CharField(max_length=200)),
                ('author_Name', models.CharField(max_length=100)),
                ('descripton', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
